### ISSUE TITLE
Why does this program take up a lot of CPU resources

### ISSUE THREAD

**Issue by zyf1040895256** [memad73/DualSR#2]
thank you for your good job!
This is my question.
Why is CPU utilization high？？？

**Comment by memad73** [comment]
Hi, thanks for your question.
I believe that the CPU utilization is high because the CPU is responsible for preparing training data.

**Comment by zyf1040895256** [comment]
> Hi, thanks for your question.
> I believe that the CPU utilization is high because the CPU is responsible for preparing training data.

Thank you for your reply.
